// The data object behind plugin/source/core/generated/shared.json.
import { CIRCUITS } from '../../src/data/timing.ts'
import { GM_NOTES } from '../../src/audio/export.ts'
import {
  CHOKE_FADE_SEC, MASTER_GAIN_DB, MAX_VOICES, OUTPUT_GAIN_MAX_DB, OUTPUT_GAIN_MIN_DB, STOP_FADE_SEC,
} from '../../src/audio/engine.ts'
import { MAX_BOOST_DB, MAX_CUT_DB, PEAK_CEILING_DB, TARGET_LUFS } from '../../src/audio/loudness.ts'
import { EFFECTIVE_PITCH_MAX_CENTS, EFFECTIVE_PITCH_MIN_CENTS, PITCH_MAX_CENTS, PITCH_MIN_CENTS } from '../../src/audio/pitch.ts'
import { LATE_LIMIT_SEC } from '../../src/audio/scheduler.ts'
import { BPM_DEFAULT, BPM_MAX, BPM_MIN, STEPS, TRACK_GAIN_MAX_DB, TRACK_GAIN_MIN_DB } from '../../src/state/pattern.ts'

export function sharedData() {
  return {
    note: 'Generated by plugin/scripts/gen-shared.ts from src/. Do not edit.',
    constants: {
      masterGainDb: MASTER_GAIN_DB,
      maxVoices: MAX_VOICES,
      stopFadeSec: STOP_FADE_SEC,
      chokeFadeSec: CHOKE_FADE_SEC,
      outputGainMinDb: OUTPUT_GAIN_MIN_DB,
      outputGainMaxDb: OUTPUT_GAIN_MAX_DB,
      targetLufs: TARGET_LUFS,
      peakCeilingDb: PEAK_CEILING_DB,
      maxBoostDb: MAX_BOOST_DB,
      maxCutDb: MAX_CUT_DB,
      pitchMinCents: PITCH_MIN_CENTS,
      pitchMaxCents: PITCH_MAX_CENTS,
      effectivePitchMinCents: EFFECTIVE_PITCH_MIN_CENTS,
      effectivePitchMaxCents: EFFECTIVE_PITCH_MAX_CENTS,
      lateLimitSec: LATE_LIMIT_SEC,
      steps: STEPS,
      bpmMin: BPM_MIN,
      bpmMax: BPM_MAX,
      bpmDefault: BPM_DEFAULT,
      trackGainMinDb: TRACK_GAIN_MIN_DB,
      trackGainMaxDb: TRACK_GAIN_MAX_DB,
    },
    gmNotes: GM_NOTES,
    // Only what the audio thread needs: swing positions and jitter models. Sources stay in src/data/timing.ts.
    circuits: Object.fromEntries(
      Object.entries(CIRCUITS)
        .sort(([a], [b]) => (a < b ? -1 : 1))
        .map(([id, c]) => [id, {
          summary: c.summary,
          swing: c.swing ? { grids: c.swing.grids } : null,
          jitter: c.jitter
            ? c.jitter.kind === 'poll'
              ? { kind: 'poll', pollMs: c.jitter.pollMs, maxMs: c.jitter.maxMs }
              : { kind: 'measured', maxMs: c.jitter.maxMs, ...(c.jitter.meanMs !== undefined ? { meanMs: c.jitter.meanMs } : {}) }
            : null,
        }]),
    ),
  }
}
