import { describe, it, expect } from 'vitest'
import { patternReducer, newPatternState, clampBpm, BPM_MIN, BPM_MAX, isSaved, toPattern, fromPattern, PAGE_SIZE, STEPS, TRACK_GAIN_MAX_DB, hitGainDb, hitPitchCents, fullLevels, zeroStepPitches } from '../src/state/pattern'
import { PITCH_MIN_CENTS, PITCH_MAX_CENTS, clampPitchCents, pitchRate } from '../src/audio/pitch'
import type { KitManifest } from '../src/contract/types'

const kit = (id: string, slots: string[]): KitManifest => ({
  schemaVersion: 1, id, machineId: 'm', label: id, revision: '0123456789abcdef',
  slots: slots.map((s) => ({
    id: s, label: s, category: 'percussion', icon: 'percussion', defaultSampleId: `${id}-${s}`,
    sampleIds: [`${id}-${s}`], chokeGroup: null, gainDb: 0,
  })) as unknown as KitManifest['slots'],
  samples: slots.map((s) => ({
    id: `${id}-${s}`, blobSha256: 'a'.repeat(64), url: 'x.wav', bytes: 1, durationSec: 1, channels: 1, sampleRate: 44100, gainDb: 0, peakDbfs: null,
  })) as unknown as KitManifest['samples'],
})

describe('pattern reducer', () => {
  const a = kit('kit-a', ['kick', 'snare', 'hat-closed'])
  it('saves swing, defaults older patterns to straight, and marks groove edits unsaved', () => {
    let state = newPatternState(a, 'swing')
    const old = toPattern(state)
    expect(old.swing).toBeUndefined()
    expect(fromPattern(old, true).swing).toBe(50)
    expect(fromPattern(old, true).swingGrid).toBe(16)
    state = patternReducer(state, { type: 'markSaved' })
    state = patternReducer(state, { type: 'setSwing', swing: 63 })
    state = patternReducer(state, { type: 'setSwingGrid', grid: 8 })
    expect(isSaved(state)).toBe(false)
    const back = fromPattern(toPattern(state), true)
    expect(back.swing).toBe(63)
    expect(back.swingGrid).toBe(8)
    expect(patternReducer(state, { type: 'setSwing', swing: 90 }).swing).toBe(75)
    expect(patternReducer(state, { type: 'setSwing', swing: NaN }).swing).toBe(50)
  })
  it('starts empty at 120 BPM named UNTITLED with a track per slot', () => {
    const s = newPatternState(a, 'p1')
    expect(s.bpm).toBe(120)
    expect(s.name).toBe('UNTITLED')
    expect(Object.keys(s.tracks)).toEqual(['kick', 'snare', 'hat-closed'])
    expect(s.tracks.kick.steps).toHaveLength(16)
    expect(s.tracks.kick.steps.every((x) => !x)).toBe(true)
  })
  it('toggles steps only on the given slot and ignores out-of-range steps', () => {
    let s = newPatternState(a, 'p1')
    s = patternReducer(s, { type: 'toggleStep', slotId: 'kick', step: 15, sampleId: 'kit-a-kick' })
    expect(s.tracks.kick.steps[15]).toBe(true)
    expect(s.tracks.snare.steps.some(Boolean)).toBe(false)
    const same = patternReducer(s, { type: 'toggleStep', slotId: 'kick', step: 16, sampleId: 'x' })
    expect(same).toBe(s)
  })
  it('page edits are isolated: editing page 2 key 1 changes step 9 only', () => {
    let s = newPatternState(a, 'p1')
    s = patternReducer(s, { type: 'toggleStep', slotId: 'snare', step: PAGE_SIZE + 0, sampleId: 'kit-a-snare' })
    expect(s.tracks.snare.steps.map((x, i) => (x ? i : -1)).filter((i) => i >= 0)).toEqual([8])
  })
  it('clamps BPM to 40–240 integers', () => {
    expect(clampBpm(10)).toBe(BPM_MIN)
    expect(clampBpm(999)).toBe(BPM_MAX)
    expect(clampBpm(120.6)).toBe(121)
    expect(clampBpm(NaN)).toBe(120)
    let s = newPatternState(a, 'p1')
    s = patternReducer(s, { type: 'setBpm', bpm: 240 })
    s = patternReducer(s, { type: 'nudgeBpm', delta: 1 })
    expect(s.bpm).toBe(240)
    s = patternReducer(s, { type: 'setBpm', bpm: 40 })
    s = patternReducer(s, { type: 'nudgeBpm', delta: -1 })
    expect(s.bpm).toBe(40)
  })
  it('preserves steps for slots the new kit lacks and restores them on return', () => {
    const b = kit('kit-b', ['kick'])
    let s = newPatternState(a, 'p1')
    s = patternReducer(s, { type: 'toggleStep', slotId: 'snare', step: 4, sampleId: 'kit-a-snare' })
    s = patternReducer(s, { type: 'toggleStep', slotId: 'kick', step: 0, sampleId: 'kit-a-kick' })
    s = patternReducer(s, { type: 'bindKit', kit: b })
    expect(s.kitId).toBe('kit-b')
    expect(s.tracks.kick.sampleId).toBe('kit-b-kick')
    expect(s.tracks.kick.steps[0]).toBe(true)
    expect(s.tracks.snare.steps[4]).toBe(true) // silenced, not deleted
    s = patternReducer(s, { type: 'bindKit', kit: a })
    expect(s.tracks.snare.steps[4]).toBe(true)
  })
  it('tracks saved state by edit count', () => {
    let s = newPatternState(a, 'p1')
    expect(isSaved(s)).toBe(false)
    s = patternReducer(s, { type: 'markSaved' })
    expect(isSaved(s)).toBe(true)
    s = patternReducer(s, { type: 'rename', name: 'Beat' })
    expect(isSaved(s)).toBe(false)
  })
  it('round-trips through the contract Pattern shape', () => {
    let s = newPatternState(a, 'p1')
    s = patternReducer(s, { type: 'toggleStep', slotId: 'kick', step: 3, sampleId: 'kit-a-kick' })
    s = patternReducer(s, { type: 'setBpm', bpm: 97 })
    const p = toPattern(s, new Date('2026-09-30T00:00:00Z'))
    expect(p.tracks.every((t) => t.steps.length === 16)).toBe(true)
    const back = fromPattern(p, true)
    expect(back.bpm).toBe(97)
    expect(back.tracks.kick.steps[3]).toBe(true)
    expect(isSaved(back)).toBe(true)
  })
})

describe('volume and loop length', () => {
  const k = kit('kit-v', ['kick', 'snare'])
  it('clamps track gain, treats the bottom stop as off, and round-trips through Pattern', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setTrackGain', slotId: 'kick', gainDb: 20 })
    expect(s.tracks.kick.gainDb).toBe(TRACK_GAIN_MAX_DB)
    s = patternReducer(s, { type: 'setTrackGain', slotId: 'snare', gainDb: -99 })
    expect(s.tracks.snare.gainDb).toBe(-Infinity)
    s = patternReducer(s, { type: 'setStepLevel', slotId: 'kick', step: 3, level: 0.5 })
    s = patternReducer(s, { type: 'setLength', length: 8 })
    const p = toPattern(s)
    expect(p.length).toBe(8)
    expect(p.tracks.find((t) => t.slotId === 'snare')!.gainDb).toBe(-60)
    const back = fromPattern(p, false)
    expect(back.tracks.snare.gainDb).toBe(-Infinity)
    expect(back.tracks.kick.gainDb).toBe(TRACK_GAIN_MAX_DB)
    expect(back.tracks.kick.levels[3]).toBe(0.5)
    expect(back.length).toBe(8)
  })
  it('loads patterns saved before volume fields existed with defaults', () => {
    const back = fromPattern({ schemaVersion: 1, id: 'o', name: 'OLD', kitId: 'kit-v', kitRevision: '0123456789abcdef', bpm: 100,
      tracks: [{ slotId: 'kick', sampleId: 'kit-v-kick', steps: new Array(16).fill(false) as never }], updatedAt: '2026-09-30T00:00:00Z' }, true)
    expect(back.length).toBe(16)
    expect(back.tracks.kick.gainDb).toBe(0)
    expect(back.tracks.kick.levels.every((l) => l === 1)).toBe(true)
  })
  it('computes hit gain from track gain and squared step level', () => {
    expect(hitGainDb({ gainDb: -6, levels: fullLevels() }, 0)).toBeCloseTo(-6)
    const levels = fullLevels()
    levels[2] = 0.5
    expect(hitGainDb({ gainDb: 0, levels }, 2)).toBeCloseTo(-12.04, 1)
    levels[3] = 0
    expect(hitGainDb({ gainDb: 0, levels }, 3)).toBe(-Infinity)
    expect(hitGainDb({ gainDb: -Infinity, levels }, 0)).toBe(-Infinity)
    expect(hitGainDb({ gainDb: 3, levels }, null)).toBe(3)
  })
  it('reset restores drum volume and step levels', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setTrackGain', slotId: 'kick', gainDb: -10 })
    s = patternReducer(s, { type: 'setStepLevel', slotId: 'kick', step: 0, level: 0.2 })
    s = patternReducer(s, { type: 'resetTrackVolume', slotId: 'kick' })
    expect(s.tracks.kick.gainDb).toBe(0)
    expect(s.tracks.kick.levels[0]).toBe(1)
  })
})

describe('pitch', () => {
  const k = kit('kit-p', ['kick', 'snare'])
  it('defaults overall and step pitch to zero, with fresh arrays', () => {
    const s = newPatternState(k, 'p')
    expect(s.pitchCents).toBe(0)
    expect(s.tracks.kick.stepPitchCents).toEqual(new Array(STEPS).fill(0))
    expect(s.tracks.kick.stepPitchCents).not.toBe(s.tracks.snare.stepPitchCents)
    expect(zeroStepPitches()).not.toBe(zeroStepPitches())
  })
  it('clamps cents to integers within ±1200 and rejects malformed values', () => {
    expect(clampPitchCents(50.4)).toBe(50)
    expect(clampPitchCents(-50.6)).toBe(-51)
    expect(clampPitchCents(99999)).toBe(PITCH_MAX_CENTS)
    expect(clampPitchCents(-99999)).toBe(PITCH_MIN_CENTS)
    expect(clampPitchCents('120')).toBe(0)
    expect(clampPitchCents(NaN)).toBe(0)
    expect(clampPitchCents(Infinity)).toBe(0)
    expect(clampPitchCents(null)).toBe(0)
    expect(clampPitchCents(undefined)).toBe(0)
    expect(clampPitchCents({})).toBe(0)
  })
  it('computes playback rate from effective cents, independent of the control clamp', () => {
    expect(pitchRate(0)).toBe(1)
    expect(pitchRate(1200)).toBeCloseTo(2)
    expect(pitchRate(-1200)).toBeCloseTo(0.5)
    expect(pitchRate(2400)).toBe(4)
    expect(pitchRate(-2400)).toBeCloseTo(0.25)
    expect(pitchRate(2401)).toBe(4)
    expect(pitchRate(-99999)).toBeCloseTo(0.25)
    expect(pitchRate(NaN)).toBe(1)
    expect(pitchRate(Infinity)).toBe(1)
  })
  it('setPitch is a no-op for identical values and ignores out-of-range input by clamping', () => {
    let s = newPatternState(k, 'p')
    const same = patternReducer(s, { type: 'setPitch', pitchCents: 0 })
    expect(same).toBe(s)
    s = patternReducer(s, { type: 'setPitch', pitchCents: 500 })
    expect(s.pitchCents).toBe(500)
    const again = patternReducer(s, { type: 'setPitch', pitchCents: 500 })
    expect(again).toBe(s)
    expect(patternReducer(s, { type: 'setPitch', pitchCents: 99999 }).pitchCents).toBe(PITCH_MAX_CENTS)
  })
  it('sets step offsets independently per slot and step, rejecting bad indexes and missing tracks', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 5, pitchCents: -500 })
    expect(s.tracks.kick.stepPitchCents[5]).toBe(-500)
    expect(s.tracks.snare.stepPitchCents[5]).toBe(0)
    expect(patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 16, pitchCents: 100 })).toBe(s)
    expect(patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 1.5, pitchCents: 100 })).toBe(s)
    expect(patternReducer(s, { type: 'setStepPitch', slotId: 'missing', step: 1, pitchCents: 100 })).toBe(s)
    const again = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 5, pitchCents: -500 })
    expect(again).toBe(s)
  })
  it('resets an instrument step array only when it is not already zero', () => {
    let s = newPatternState(k, 'p')
    expect(patternReducer(s, { type: 'resetStepPitches', slotId: 'kick' })).toBe(s)
    expect(patternReducer(s, { type: 'resetStepPitches', slotId: 'missing' })).toBe(s)
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 0, pitchCents: 200 })
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'snare', step: 0, pitchCents: 100 })
    s = patternReducer(s, { type: 'resetStepPitches', slotId: 'kick' })
    expect(s.tracks.kick.stepPitchCents.every((c) => c === 0)).toBe(true)
    expect(s.tracks.snare.stepPitchCents[0]).toBe(100)
  })
  it('composes overall and per-step pitch, ignoring step or missing track', () => {
    let s = patternReducer(newPatternState(k, 'p'), { type: 'setPitch', pitchCents: 300 })
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 5, pitchCents: -1200 })
    expect(hitPitchCents(s, s.tracks.kick, 5)).toBe(-900)
    expect(hitPitchCents(s, s.tracks.kick, 4)).toBe(300)
    expect(hitPitchCents(s, s.tracks.kick, null)).toBe(300)
    expect(hitPitchCents(s, undefined, 5)).toBe(300)
  })
  it('resetTrackVolume leaves pitch untouched', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setPitch', pitchCents: 100 })
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 2, pitchCents: 300 })
    s = patternReducer(s, { type: 'resetTrackVolume', slotId: 'kick' })
    expect(s.pitchCents).toBe(100)
    expect(s.tracks.kick.stepPitchCents[2]).toBe(300)
  })
  it('keeps pitch through clear and step toggles', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setPitch', pitchCents: 250 })
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 0, pitchCents: 50 })
    s = patternReducer(s, { type: 'toggleStep', slotId: 'kick', step: 0, sampleId: 'x' })
    s = patternReducer(s, { type: 'clear' })
    expect(s.tracks.kick.steps.every((x) => !x)).toBe(true)
    expect(s.pitchCents).toBe(250)
    expect(s.tracks.kick.stepPitchCents[0]).toBe(50)
  })
  it('keeps step offsets through kit changes and preserves absent tracks', () => {
    const b = kit('kit-pb', ['kick'])
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'snare', step: 8, pitchCents: -300 })
    s = patternReducer(s, { type: 'bindKit', kit: b })
    expect(s.tracks.snare.stepPitchCents[8]).toBe(-300)
    expect(s.tracks.kick.stepPitchCents.every((c) => c === 0)).toBe(true)
    s = patternReducer(s, { type: 'bindKit', kit: k })
    expect(s.tracks.snare.stepPitchCents[8]).toBe(-300)
  })
  it('round-trips sparse pitch fields and keeps offsets outside an 8-step loop', () => {
    let s = newPatternState(k, 'p')
    s = patternReducer(s, { type: 'setLength', length: 8 })
    s = patternReducer(s, { type: 'setPitch', pitchCents: 200 })
    s = patternReducer(s, { type: 'setStepPitch', slotId: 'kick', step: 12, pitchCents: 700 })
    const p = toPattern(s)
    expect(p.pitchCents).toBe(200)
    expect(p.tracks.find((t) => t.slotId === 'kick')!.stepPitchCents![12]).toBe(700)
    expect(p.tracks.find((t) => t.slotId === 'snare')!.stepPitchCents).toBeUndefined()
    const back = fromPattern(p, false)
    expect(back.pitchCents).toBe(200)
    expect(back.length).toBe(8)
    expect(back.tracks.kick.stepPitchCents[12]).toBe(700)
    expect(back.tracks.snare.stepPitchCents.every((c) => c === 0)).toBe(true)
  })
  it('omits zero pitch from serialization and reads legacy patterns without pitch', () => {
    const p = toPattern(newPatternState(k, 'p'))
    expect(p.pitchCents).toBeUndefined()
    expect(p.tracks.every((t) => t.stepPitchCents === undefined)).toBe(true)
    const legacy = fromPattern({ schemaVersion: 1, id: 'l', name: 'L', kitId: 'kit-p', kitRevision: '0123456789abcdef', bpm: 120,
      tracks: [{ slotId: 'kick', sampleId: 'kit-p-kick', steps: new Array(16).fill(false) as never }], updatedAt: '2026-09-30T00:00:00Z' }, true)
    expect(legacy.pitchCents).toBe(0)
    expect(legacy.tracks.kick.stepPitchCents).toHaveLength(16)
    expect(legacy.tracks.kick.stepPitchCents.every((c) => c === 0)).toBe(true)
  })
  it('normalizes malformed imported pitch fields without throwing', () => {
    const back = fromPattern({
      schemaVersion: 1, id: 'm', name: 'M', kitId: 'kit-p', kitRevision: '0123456789abcdef', bpm: 120,
      pitchCents: 'x' as never,
      tracks: [{ slotId: 'kick', sampleId: 'kit-p-kick', steps: new Array(16).fill(false) as never,
        stepPitchCents: [50, NaN, Infinity, '7', {}, null, -300, 99999, 1.5, ...new Array(7).fill(0)] as never }],
      updatedAt: '2026-09-30T00:00:00Z',
    }, true)
    expect(back.pitchCents).toBe(0)
    const offsets = back.tracks.kick.stepPitchCents
    expect(offsets).toHaveLength(16)
    expect(offsets[0]).toBe(50)
    expect(offsets[1]).toBe(0)
    expect(offsets[2]).toBe(0)
    expect(offsets[3]).toBe(0)
    expect(offsets[4]).toBe(0)
    expect(offsets[5]).toBe(0)
    expect(offsets[6]).toBe(-300)
    expect(offsets[7]).toBe(PITCH_MAX_CENTS)
    expect(offsets[8]).toBe(2)
    expect(offsets[15]).toBe(0)
  })
})
