// GENERATED by scripts/catalog/gen-types.ts from catalog/schema. Do not edit.
/**
 * Small searchable index. Served with revalidation at catalog/index.json. No full sample inventory.
 */

export interface CatalogIndex {
  schemaVersion: 1
  /**
   * First 16 hex chars of SHA-256 over compact UTF-8 JSON with recursively sorted object keys, array order preserved, and the root `revision` field omitted.
   */
  revision: string
  machines: Machine[]
  kits: KitEntry[]
  redirects: {
    machines: RedirectMap
    kits: RedirectMap
    samples: RedirectMap
    [k: string]: unknown
  }
  /**
   * URL relative to the configured catalog base URL. No scheme, no leading slash, no `..` or `.` segments, no backslashes, no query or fragment.
   */
  creditsUrl: string
  [k: string]: unknown
}

export interface Machine {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  manufacturer: string
  model: string
  displayName: string
  aliases: string[]
  kind: 'drum-machine' | 'keyboard' | 'synth' | 'module' | 'sampler' | 'unknown'
  identityStatus: 'provisional' | 'verified' | 'unresolved'
  logo: AssetRef | null
  photo: AssetRef | null
  /**
   * Short sourced history of the machine (50-100 words, plain prose), shown in machine details and as a preview in the library. Null until written and reviewed. Evidence stays in catalog/research/history/.
   */
  history: {
    text: string
    /**
     * @minItems 1
     * @maxItems 6
     */
    sources:
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
      | [
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          },
          {
            title: string
            url: string
            [k: string]: unknown
          }
        ]
    [k: string]: unknown
  } | null
  [k: string]: unknown
}
/**
 * Runtime reference to a published image. Logos are transparent PNGs. Missing art is null at the use site, never a broken URL.
 */

export interface AssetRef {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  /**
   * URL relative to the configured catalog base URL. No scheme, no leading slash, no `..` or `.` segments, no backslashes, no query or fragment.
   */
  url: string
  /**
   * Full lowercase hex SHA-256 of the served bytes.
   */
  sha256: string
  width: number
  height: number
  alt: string
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  creditId: string
  [k: string]: unknown
}

export interface KitEntry {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  machineId: string
  label: string
  /**
   * First 16 hex chars of SHA-256 over compact UTF-8 JSON with recursively sorted object keys, array order preserved, and the root `revision` field omitted.
   */
  revision: string
  /**
   * URL relative to the configured catalog base URL. No scheme, no leading slash, no `..` or `.` segments, no backslashes, no query or fragment.
   */
  url: string
  [k: string]: unknown
}
/**
 * Old ID -> current ID. Graph must be acyclic.
 */

export interface RedirectMap {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  [k: string]: string
}

/**
 * One sample collection/preset. Served immutably at kits/<id>/<revision>.json.
 */

export interface KitManifest {
  schemaVersion: 1
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  machineId: string
  label: string
  /**
   * First 16 hex chars of SHA-256 over compact UTF-8 JSON with recursively sorted object keys, array order preserved, and the root `revision` field omitted.
   */
  revision: string
  /**
   * @minItems 1
   */
  slots: [Slot, ...Slot[]]
  /**
   * @minItems 1
   */
  samples: [Sample, ...Sample[]]
  [k: string]: unknown
}
/**
 * One instrument role in a kit. `id` is the semantic role (kick, snare, hat-closed, hat-open, crash, ride, clap, rim, tom-low, tom-mid, tom-high, then stable named percussion roles), unique per kit.
 */

export interface Slot {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  label: string
  category: 'kick' | 'snare' | 'hat' | 'cymbal' | 'tom' | 'clap' | 'rim' | 'percussion' | 'fx' | 'unknown'
  icon: 'kick' | 'snare' | 'hat-closed' | 'hat-open' | 'cymbal' | 'tom' | 'clap' | 'rim' | 'percussion'
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  defaultSampleId: string
  /**
   * Editorial variant order. Must include defaultSampleId.
   *
   * @minItems 1
   *
   * Items: Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  sampleIds: [string, ...string[]]
  /**
   * v1 convention: both hat slots use "hi-hat"; hat-closed stops older hat-open voices, not vice versa. Other groups have no runtime effect yet.
   */
  chokeGroup: string | null
  /**
   * Gain offset in dB. Bounded to keep playback safe.
   */
  gainDb: number
  [k: string]: unknown
}
/**
 * One playable one-shot. URL is supplied by the producer, never inferred.
 */

export interface Sample {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  id: string
  /**
   * Optional display label for the variant list.
   */
  label?: string
  /**
   * Full lowercase hex SHA-256 of the served bytes.
   */
  blobSha256: string
  /**
   * URL relative to the configured catalog base URL. No scheme, no leading slash, no `..` or `.` segments, no backslashes, no query or fragment.
   */
  url: string
  bytes: number
  durationSec: number
  channels: number
  sampleRate: number
  /**
   * Gain offset in dB. Bounded to keep playback safe.
   */
  gainDb: number
  peakDbfs: number | null
  [k: string]: unknown
}

/**
 * A saved one-bar pattern of 16 steps; playback may loop the first 8. Missing sounds remain recoverable; never silently replace a removed variant. Optional fields default as documented so older saved patterns stay valid.
 */

export interface Pattern {
  schemaVersion: 1
  /**
   * Internal UUID, never the editable name.
   */
  id: string
  name: string
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  kitId: string
  /**
   * First 16 hex chars of SHA-256 over compact UTF-8 JSON with recursively sorted object keys, array order preserved, and the root `revision` field omitted.
   */
  kitRevision: string
  bpm: number
  /**
   * Playback swing: first note's percentage of a pair, 50 is straight. Default 50. App groove control, not a hardware preset emulation.
   */
  swing?: number
  /**
   * Swing note division. Default 16. Eighth-note swing delays steps 3-4 of each four-step group; sixteenth-note swing delays every second step.
   */
  swingGrid?: 8 | 16
  /**
   * Apply the current machine's documented hardware timing (swing tick positions, measured step jitter) when the app has data for it. Default false.
   */
  circuit?: boolean
  tracks: Track[]
  /**
   * ISO 8601 UTC timestamp.
   */
  updatedAt: string
  /**
   * Loop length in steps. Default 16. With 8, steps 9-16 are kept but not played.
   */
  length?: 8 | 16
  /**
   * Overall sample tuning in integer cents for every instrument in this pattern (100 cents = 1 semitone). Raised pitch shortens the sample. Default 0. Adds to each track's per-step offsets.
   */
  pitchCents?: number
  [k: string]: unknown
}

export interface Track {
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  slotId: string
  /**
   * Stable lowercase ASCII kebab-case identifier, assigned once.
   */
  sampleId: string
  /**
   * @minItems 16
   * @maxItems 16
   */
  steps: [
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean,
    boolean
  ]
  /**
   * Drum volume offset in dB applied to every hit of this track. Default 0.
   */
  gainDb?: number
  /**
   * Per-step level, 0 (silent) to 1 (full). Amplitude = level squared. Default all 1.
   *
   * @minItems 16
   * @maxItems 16
   */
  levels?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ]
  /**
   * Per-step pitch offsets in integer cents added to the pattern's overall pitch (100 cents = 1 semitone). Exactly 16 entries; default all 0. Offsets survive a step being off and remain editable outside the 8-step loop.
   *
   * @minItems 16
   * @maxItems 16
   */
  stepPitchCents?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ]
  [k: string]: unknown
}

/**
 * Published credits keyed by creditId. Research evidence stays out of runtime files.
 */

export interface Credits {
  schemaVersion: 1
  credits: {
    [k: string]: {
      display: string
      sourceUrl: string | null
      /**
       * Stated terms, or "unknown".
       */
      usageTerms: string
      [k: string]: unknown
    }
  }
  [k: string]: unknown
}
