// Generates src/contract/types.ts from catalog/schema/*.schema.json.
// Run after any schema change: `npm run catalog:types`.
import { compile } from 'json-schema-to-typescript'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const schemaDir = path.resolve('catalog/schema')
const roots = ['index', 'kit', 'pattern', 'credits']

const header = `// GENERATED by scripts/catalog/gen-types.ts from catalog/schema. Do not edit.\n`
let out = header
const seen = new Set<string>()
for (const name of roots) {
  const file = path.join(schemaDir, `${name}.schema.json`)
  const schema = JSON.parse(await readFile(file, 'utf8'))
  const ts = await compile(schema, name, {
    bannerComment: '',
    cwd: schemaDir,
    additionalProperties: true,
    declareExternallyReferenced: true,
    style: { singleQuote: true, semi: false },
  })
  // json2ts re-emits shared declarations per root; keep the first of each.
  for (const block of ts.split(/\n(?=export )/)) {
    const m = block.match(/^export (?:interface|type) (\w+)/)
    if (m) {
      if (seen.has(m[1])) continue
      seen.add(m[1])
    }
    out += block.trim() + '\n\n'
  }
}
await writeFile('src/contract/types.ts', out.trimEnd() + '\n')
console.log(`wrote src/contract/types.ts (${seen.size} declarations)`)
